### ISSUE TITLE
Conditional selection of list id

### ISSUE THREAD

**Issue by gmarec** [ibericode/mailchimp-top-bar#25]
I have for the moment write down this dirty code, because I found no way to modify options with your plugin :

		$email_type = apply_filters( 'mctb_email_type', 'html' );
		$listID = $this->options->get( 'list' );
		$request_uri = $_SERVER['REQUEST_URI'];
		if (preg_match("/^\/blog\/tous-les-lieux\//", $request_uri ))
			$listID = "abcde1f23a";

		$result = $api->subscribe( $listID, $email, $merge_vars, $email_type, $this->options->get( 'double_optin' ) );

		do_action( 'mc4wp_subscribe', $email, $this->options->get( 'list' ), $merge_vars, ( $result === true ), 'form', 'top-bar' );

Do you have a better way to do it ? Tx

**Comment by dannyvankooten** [comment]
Hi @gmarec,

Sorry, I'm only seeing this now. I've just pushed a commit to the repository which makes this a bit more easy so you don't have to edit the core plugin files.

```php
add_filter( 'mctb_mailchimp_list', function( $list_id ) {
	$request_uri = $_SERVER['REQUEST_URI'];
	if( preg_match( "/^\/blog\/tous-les-lieux\//", $request_uri ) ) {
		 $list_id = "abcde1f23a";
	}

	return $list_id;       
} );
```

We're hoping to push out an update later this week, but you can always just download the development version here from GitHub. :)
