### ISSUE TITLE
Top Bar doesn't show in any browser type

### ISSUE THREAD

**Issue by jkurzner** [ibericode/mailchimp-top-bar#29]
Looks like the top bar is defaulting to display:none.  Is there a setting I am missing?

**Comment by dannyvankooten** [comment]
Hi jkurzner,

That's right, the bar is shown using JavaScript (or will stay hidden if it was dismissed before). If you have JS enabled, the bar (or the toggle icon) should show up. 

Do you have a link to your site so I can take a look at any JS errors?

**Comment by jkurzner** [comment]
Hey Danny,

 

I had to disable it so that I could move on.  I’ll try to recreate it on another site so I can send you the information.

**Comment by arnelap** [comment]
Hi,

We use Git issues only for bugs and feature requests and are usually not able to respond to support requests posted as Git Issue in a timely manner.

Please create a support ticket here: https://wordpress.org/support/plugin/mailchimp-top-bar
Please include a link to a live website where we can test the form as it's most likely a compatibility issue with your theme.

Thank you!
