### ISSUE TITLE
Appearance tab isn't aligned properly

### ISSUE THREAD

**Issue by chantalcoolsma** [ibericode/mailchimp-top-bar#44]
The appearance tab is aligned properly:

![schermafbeelding 2015-11-23 om 21 24 41](https://cloud.githubusercontent.com/assets/867632/11348787/dc7affb6-9228-11e5-8c1d-e37e538889b7.png)

When you change the two `<div class="col-2">` into `<div class="col">` it is shown ok:

![schermafbeelding 2015-11-23 om 21 25 26](https://cloud.githubusercontent.com/assets/867632/11348807/fa98639e-9228-11e5-91c4-f1592db39ac9.png)

**Comment by dannyvankooten** [comment]
Hey @chantalcoolsma , are you on the latest version of MailChimp Top Bar? We pushed out an update this Sunday that I think addresses this. I can't seem to replicate using the new version.

**Comment by chantalcoolsma** [comment]
Version 1.2.4

**Comment by dannyvankooten** [comment]
And it's not cache? Sorry to ask.. :-)

**Comment by chantalcoolsma** [comment]
Nope fresh install after I updated MC4WP to version 3.0
