### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by formastudio1** [ibericode/mailchimp-top-bar#49]
After update  to version 1.26 the site does not work (white page admin and frontpage too). WP 4.4, PHP 5.6. (With version 1.25 is everything ok).

Fatal error: Call to undefined method MailChimp\TopBar\Plugin::init() in /.../public_html/wp-content/plugins/mailchimp-top-bar/mailchimp-top-bar.php on line 64

**Comment by dannyvankooten** [comment]
Hi @formastudio1 ,

That's weird, it looks like you somehow have a partial update installed. The referenced file is still at the old version while another file is already at the newer version.

Could you try re-downloading the plugin from WordPress.org to see if that fixes your issue?

All your settings will be preverved, so you won't need to reconfigure the plugin.

**Comment by formastudio1** [comment]
Hello @dannyvankooten ,

I have followed your instructions but is still lists the mistake.

If I disable the plugin "MailChimp for WordPress", plugin "MailChimp Top Bar" updating fine. But once I activate the plugin "MailChimp for WordPress", the page is blank.

Is there any conflict between the plugins?

**Comment by dannyvankooten** [comment]
Hi @formastudio1 ,

There is no conflict between the plugins, something in the download or update process is causing the conflict. Are you seeing any errors when installing or updating the plugin?

Can you please take the following steps to make sure the correct plugin files are downloaded from WordPress.org?

1. Go to WP Admin > Plugins and deactivate MailChimp Top Bar.
2. Then, click "Delete" below the plugin name to completely remove the plugin.
3. Once the plugin is deleted, re-install the plugin by going to "Add Plugin"
4. Search WordPress.org for "MailChimp Top Bar"
5. Install & active the plugin.

I just took those steps with MailChimp for WordPress 3.0.9 already installed & activated and things are definitely working as expected. Let me know if that fixes it please!

**Comment by formastudio1** [comment]
Hi @dannyvankooten ,
1. I followed you instruction, but is still lists the mistake.
2. I deleted both plugin. I disabled all plugins. Subsequently, again, I install both plugins (Mailchimp for WP and Mailchimp Top Bar). After activating the plugin Mailchimp Top Bar v1.26 the page is white. Problem was not solved.
Maybe I should erase something from the MySQL database after deleting the plugin.

**Comment by dannyvankooten** [comment]
Hi @formastudio1 ,

That is very weird, it seems that for some reason the main plugin file is not being overwritten. Do you have FTP access to your site by any chance? If so, could you manually delete the plugin files?

Alternatively, please send us an email at support@mc4wp.com so we can take a closer look at this. 

Thanks in advance!
