### ISSUE TITLE
new update 1.2.8 can not hide bottom bar once open

### ISSUE THREAD

**Issue by mackag** [ibericode/mailchimp-top-bar#53]
when page loads there is the arrow to open the bottom bar although then the arrow disappears and can not minimise the bottom bar like you used to.

Also using on listify theme and can not focus mouse onto the email text field as looks to be under a image layer, once scrolled away from the image being under the bottom bar then can focus curser on input field

**Comment by dannyvankooten** [comment]
Hi @mackag ,

Thank you for the heads up - this should be fixed in version 1.2.9 which we just released!

**Comment by mackag** [comment]
thanks mate

installed and looks good!

cheers

Glenn
