### ISSUE TITLE
Can I show the bar on specific two location, not just top or bottom? A simple example would be great! :-)

### ISSUE THREAD

**Issue by atikrahman146** [ibericode/mailchimp-top-bar#55]
I want to hide form completely to the viewer after successful subscription. But main mailchimp form doesn't have this option so want to use the top-bar plugin instead of main one.

**Comment by arnelap** [comment]
Hi,

We use Git issues only for bugs and feature requests.

Please create a support ticket here: https://wordpress.org/support/plugin/mailchimp-top-bar
Please include a link to a live website where we can test the form as it's most likely a compatibility issue with your theme.

Thank you!
