### ISSUE TITLE
How do I change the color of the text in the "enter your email" field?

### ISSUE THREAD

**Issue by coreyt23** [ibericode/mailchimp-top-bar#56]
Hi, 
On my wordpress blog (coreytrevathan.com) the place to enter your email address in the MailChimp Top Bar plugin is white.  And when you try to type in your email address, the text is white.  So you can't see what you're typing in.  How do you change the color of the text in this field where people type their email address for submission?  Thank you!

**Comment by arnelap** [comment]
Hi,

We use Git issues only for bugs and feature requests.

Please create a support ticket here: https://wordpress.org/support/plugin/mailchimp-top-bar
Please include a link to a live website where we can test the form as it's most likely a compatibility issue with your theme.

Thank you!
