### ISSUE TITLE
A few issues with Plugin 

### ISSUE THREAD

**Issue by mariellacinquegrani** [ibericode/mailchimp-top-bar#61]
When displaying the bar on my site, I have two seperate issues.  One is that the placeholder text for the email field is not displaying for me.  Second is that I have "confirm email" checked off, but the 'confirm your email' text is still displaying on my bar, although the input field is not displaying.  Are there solutions to these issues? Thank you!

**Comment by mariellacinquegrani** [comment]
Can I get some help with these issues? Thanks!

**Comment by dannyvankooten** [comment]
Hi @mariellacinquegrani ,

Sorry but this is not a support forum. Can you open your issue on the WordPress.org support forums and include a link to your site so we can take an actual look at what is going on? 

Thanks in advance!
