### ISSUE TITLE
Responsive Bar

### ISSUE THREAD

**Issue by tech4him1** [ibericode/mailchimp-top-bar#63]
Do you have any plans for making the Mailchimp Top Bar fully responsive?  I have been playing around with a few different methods on a fork (https://github.com/tech4him1/mailchimp-top-bar/branches), but wasn't sure if you had anything specific that you had already tried and didn't work.

**Comment by dannyvankooten** [comment]
Hey @tech4him1 ,

How would you improve the bar's responsiveness, as in what areas do you think could do with some improvements? The bar should be reasonably responsive, except when you manually resized the window after page load although cfa2485c2cb9b1b15680ac8d12147cfb0d3d576d should fix that.

Here's what the bar looks like on common window resolutions for me.

Older smartphones.
![image](https://cloud.githubusercontent.com/assets/885856/17964494/b7c71870-6ab9-11e6-9ed8-771dd81e7a65.png)

Newer smartphones
![image](https://cloud.githubusercontent.com/assets/885856/17964483/ab614416-6ab9-11e6-91db-f9b062d8e215.png)

Default desktop view for most other screen sizes.

Let me know please!

**Comment by tech4him1** [comment]
Changing window size after load was what I was thinking of for responsiveness -- thanks for implementing that.  Desktop users probably don't do that much, but if a mobile user rotates their screen, that would change it significantly.

Also, with the window resizing, the body padding actually needs to be changed instead of just computing it.  Here is my version of that: https://github.com/tech4him1/mailchimp-top-bar/commit/c3197cb3fb571e5e3f1b0bf3b3229f012ba5342a.  Other than that, it looks great.  Thanks!

**Comment by tech4him1** [comment]
One more thing: do you think showing and hiding the bar continually on resize when the bar is hidden would cause flickering on low-powered computers?

**Comment by tech4him1** [comment]
Wow, that looks great.  Thanks for your time!
