### ISSUE TITLE
Space left by WP admin bar when scrolled on small screens.

### ISSUE THREAD

**Issue by tech4him1** [ibericode/mailchimp-top-bar#64]
WP admin bar does not scroll on screens below 600px width.  This bar does scroll when sticky, and therefore leaves a blank space above itself.

**Comment by dannyvankooten** [comment]
Hey @tech4him1 ,

Nice find... 

This will be a bit hard to solve so I opted for a temporary solution, for now. The bar is now tucked under the admin bar when the bar is sticky, so that it will only appear when people scroll down... Better than a gap, IMO. What do you think?

**Comment by tech4him1** [comment]
I don't know.  That would probably work just as well, but we would also need to take away 46px of padding from the top of the body.

**Comment by tech4him1** [comment]
Also, the open/close button is fully hidden behind the admin bar when closed.

**Comment by dannyvankooten** [comment]
@tech4him1 Yes, that's on purpose. Please see my last comment. :)

**Comment by tech4him1** [comment]
OK, sorry, I didn't realize that.

Thanks!
