### ISSUE TITLE
Spacing is not correct when extra fields added.

### ISSUE THREAD

**Issue by tech4him1** [ibericode/mailchimp-top-bar#65]
Inputs are not spaced/aligned correctly when extra fields are added.

![capture](https://cloud.githubusercontent.com/assets/20345941/18057774/9d5a8c84-6dce-11e6-8764-c7a3ca8f117e.PNG)
![capture2](https://cloud.githubusercontent.com/assets/20345941/18057773/9d5a5610-6dce-11e6-8362-d0ad2cfc1cbb.PNG)

Here is my fix, I can make a pull request, or you can do it if you have a better way: https://github.com/tech4him1/mailchimp-top-bar/commit/719bfec1277f4321eafefb15c47802074c4cadde

Reference #38.
Hope you don't mind how many issues I have been submitting.

**Comment by tech4him1** [comment]
Hope you don't mind how many issues I have been submitting.

**Comment by tech4him1** [comment]
@dannyvankooten, just making sure you got this.

**Comment by dannyvankooten** [comment]
Hey @tech4him1 ,

Nice catch, thank you. Initially we didn't want to support additional inputs out of the box but this is an easy enough change that will benefit many, so nice find. 

I took a slightly different approach and just removed the `margin-right` on small screens and bumped the label to its own line whenever the bar has multiple inputs. 

Let me know if you have any other suggestions please. :)

**Comment by tech4him1** [comment]
That works great when a single field is added, and I don't think many people would add more than one extra.  However, if they did, the boxes  would start touching (like in my second picture above), and that might be surprising.  If you added a top margin to all inputs even when they are in full-screen, that would account for that (`input, .mctb-email {margin-top: 6px;}`).  But you would then need to remove the extra top padding from `mctb-bar`.  Here is a rough up if that is not clear enough: https://github.com/tech4him1/mailchimp-top-bar/commit/1030944ecd01384aa4c4b9da3312a535ba715777.

The other way to do it is to dynamically calculate `$tablet_max`, but that would mean dynamically generated CSS after all filters were added.

That is just my thoughts on it, I was thinking it might be a little surprising if someone adds one extra field and it works, then adds another and it doesn't.
