### ISSUE TITLE
Not Showing Mailchimp Lists.

### ISSUE THREAD

**Issue by RSPaul** [ibericode/mailchimp-top-bar#68]

**Comment by RSPaul** [comment]
I have installed this plugin. And It asked me to connect my mailchimp account to wordpress. I have connected that and the plugin show that account is connected.
![10496290](https://cloud.githubusercontent.com/assets/10462640/23169975/b6858c2e-f873-11e6-9863-f5eae36fd5d4.png)
But it doesn't show any list in the drop down, when I want to choose it for the form.
![2](https://cloud.githubusercontent.com/assets/10462640/23170021/dbad7fb6-f873-11e6-8725-32e20f7bf495.png)
Even I have several lists in my mailchimp account.
![3](https://cloud.githubusercontent.com/assets/10462640/23170049/f3e52c96-f873-11e6-9f7c-8303bc3667c0.png)

**Comment by dannyvankooten** [comment]
Hi @RSPaul,

Sorry for being so late to reply, I didn't really see this issue before. I'm guessing this should be resolved by a recent version of the plugin since we've changed the way how lists are stored & fetched since then. Can you confirm please?
