### ISSUE TITLE
too much padding below the topbar, is this a bug?

### ISSUE THREAD

**Issue by yelnyaface** [ibericode/mailchimp-top-bar#69]
http://prntscr.com/ezw9v4

http://prntscr.com/ezwa40

http://prntscr.com/ezwao5

**Comment by dannyvankooten** [comment]
Hi @yelnyaface,

I'm not too sure whether this is a bug without seeing a link to your site so I can inspect the actual CSS of your theme. Do you have a link so I can take a look?

**Comment by yelnyaface** [comment]
hi, here is the link:
http://rasamalaysia.com/chili-lime-chicken/

if the user try to subscribe, the success response will generate a large padding space that will not go away:

http://prntscr.com/f03ken

**Comment by arnelap** [comment]
Hi,

I noticed the topbar is already gone from your website. 

We use Git issues only for bugs and feature requests and as you noticed we are not able to reply to support requests in a timely manner via Git issues. 

Please create a support ticket here: https://wordpress.org/support/plugin/mailchimp-top-bar
Please include a link to a live website where we can test the form as it's most likely a compatibility issue with your theme.

Thank you!
