### ISSUE TITLE
Problem/Bug When Toggling Menu Off!

### ISSUE THREAD

**Issue by blackcrossdesigns** [ibericode/mailchimp-top-bar#73]
Hello,

I am quite new to websites, and it's the first time I post for a problem as I can't seem to resolve it at all. Not always but mostly, when the bar is toggled off it leaves a white bar in it's place and it looks ugly. When it works normally it looks lovely and I want to keep the feature so it would be great if you could help me with a fix!

This is the bar it leaves behind when toggled off:
![bar](https://user-images.githubusercontent.com/31357297/29731093-c294d164-89eb-11e7-9abc-efdf80e1c866.png)

Please help! I love the plugin :(

**Comment by arnelap** [comment]
Hi,

We use Git issues only for bugs and feature requests.

Please create a support ticket here: https://wordpress.org/support/plugin/mailchimp-top-bar
Please include a link to a live website where we can test the form as it's most likely a compatibility issue with your theme.

Thank you!
