### ISSUE TITLE
Error on WordPress FAQ for the plugin

### ISSUE THREAD

**Issue by DanDawson** [ibericode/mailchimp-top-bar#74]
On this page:
https://wordpress.org/plugins/mailchimp-top-bar/

In the FAQ section there is the question **how to hide the bar on small screens?**

A portion of the answer to that question shows up as the next FAQ question instead of being included within the answer. See the attached screenshot for what I'm talking about 

<img width="677" alt="screen shot 2017-09-29 at 12 49 36 pm" src="https://user-images.githubusercontent.com/1124168/31033461-fd08c226-a514-11e7-9538-f583f635f2a1.png">

**Comment by kellenmace** [comment]
I submitted a PR that fixes this. The has character (#) in this CSS selector was being interpreted on WordPress.org as a <dt> tag, so I swapped it out with its HTML entity. Now the code block will display as intended.

**Comment by dannyvankooten** [comment]
Hey guys, thanks so much for noticing @DanDawson and fixing @kellenmace. Sorry I didn't get around to this sooner!
