### ISSUE TITLE
Add option to exclude from certain pages

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-top-bar#8]

**Comment by dannyvankooten** [comment]
For now, this is doable using the `mctb_show_bar` filter, although an easier solution should be included in the plugin.

```php
// everywhere but the contact page
add_filter( 'mctb_show_bar', function( $show ) {
    return ! is_page( 'contact' );
} );
```

Or..

```php
// just the home page
add_filter( 'mctb_show_bar', function( $show ) {
    return is_home();
} );
```

Having a look at the [Conditional Tags](https://codex.wordpress.org/Conditional_Tags) is super helpful for setting up your filter.

**Comment by esucces** [comment]
Danny, I can't this to work anymore, has that changed with the new version?

**Comment by dannyvankooten** [comment]
Hi @esuccess,

No changes here. What does your code (for the filter) look like?

**Comment by esucces** [comment]
Hi @dannyvankooten 

Today its working, must have used a wrong page id. Sorry for bothering you!
