### ISSUE TITLE
Problems with bar covering footer

### ISSUE THREAD

**Issue by RenaAdmin** [ibericode/mailchimp-top-bar#82]
I would like to have the bar placed at the bottom of my page. It looks great on mobile. But on a desktop-sized screen, it covers most of my footer so I can't see social share icons or anything that I have there. Any assistance would be appreciated!

URL: rena-fi.com

(currently, have it set to top and hiden on mobile as this seems to cover up things as well).

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
