### ISSUE TITLE
Add label to Email Field

### ISSUE THREAD

**Issue by hchouhan** [ibericode/mailchimp-top-bar#88]
Make the form more accessible by adding labels.

**Comment by hchouhan** [comment]
https://wordpress.org/support/topic/lack-of-label-impacts-accessibility/

**Comment by arnelap** [comment]
This would work I guess: 

add_action( 'mctb_before_email_field', function() {
    echo '<label for="mailchimp-top-bar__email">Email</label>';
});

**Comment by dannyvankooten** [comment]
8ad371314ee3d36286b3599cf5e3ebf72ab13a1e

Done in 2017
